import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";
import Navbar from "../components/store/Navbar";
import Hero from "../components/store/hero/Hero";
import Banner from "../components/store/Banner";
import ProductsDisplay from "../components/store/productsContainer/ProductsDisplay";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Tealade eCommerce store</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar />
        <Banner />
      </header>
      <main>
        <Hero />
        <ProductsDisplay />
      </main>
    </>
  );
};

export default Home;
