import { type NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";
import Navbar from "../components/store/Navbar";
import Hero from "../components/store/hero/Hero";
import InteractiveBanner from "../components/store/InteractiveBanner";
import ProductsDisplay from "../components/store/productsContainer/ProductsDisplay";
import productContext from "../components/context/productsContext";
import CompleteLoadingstate from "../components/store/CompleteLoadingState";
import { CurrencyType } from "../types";
import { useState } from "react";

const Home: NextPage = () => {

  const { data: products } = api.products.getAllImportedProducts.useQuery()
  const { data: categoriesWithCount } = api.products.getAllCategoriesWithProductCount.useQuery()

  const [currency, setCurrency] = useState<CurrencyType>("USD")

  if (!products || !categoriesWithCount) {
    return <CompleteLoadingstate />
  }


  return (
    <productContext.Provider value={{
      products: products,
      categoriesWIthProductCount: categoriesWithCount,
      currency,
      setCurrency: (curr: CurrencyType) => setCurrency(curr)
    }}>
      <Head>
        <title>Tealade eCommerce store</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>

        <InteractiveBanner />
        <Navbar />
      </header>
      <main>
      </main>
    </productContext.Provider>
  );
};

export default Home;
